# Generated by Django 5.0 on 2023-12-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TO DO', 'To Do'), ('DOING', 'Doing'), ('TEST', 'Test'), ('DONE', 'Done')], max_length=10)),
            ],
        ),
    ]
