# Generated by Django 5.0 on 2023-12-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='High', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('TO DO', 'To Do'), ('DOING', 'Doing'), ('TEST', 'Test'), ('DONE', 'Done')], default='Backlog', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apirest.priority'),
        ),
    ]
