# Generated by Django 5.0 on 2023-12-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_priority_alter_task_status_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(default='High', max_length=40),
        ),
    ]
